apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: varlog-daemonset
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      name: test-daemonset
  template:
    metadata:
      labels:
        name: test-daemonset
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: varlog
          mountPath: /var/log/
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log